<<<<<<< HEAD
version: '3.4'

services:
  searonweb:
    image: searonweb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
=======
version: '3.4'

services:
  searonweb:
    image: searonweb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
>>>>>>> 2311233f782c5251c94a4fa3de5970de965e3c02
