name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
    - uses: actions/checkout@v2

    - name: Setting .env
      run: |
          echo "VITE_NOTION_KEY = ${{secrets.VITE_NOTION_KEY}}" >> .env

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Pull the Docker image for caching
      run: docker pull gunho30811/searon-web:latest || true
    
    - name: Build the Docker image
      run: |
        docker build . \
        --file Dockerfile \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --cache-from=gunho30811/searon-web:latest \
        --tag gunho30811/searon-web:latest
    
    - name: Check .env content
      run: cat .env

    - name: Push the Docker image
      run: docker push gunho30811/searon-web:latest

    - name: Dispatch deploy event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        event-type: deploy
